In [1]:
import pandas as pd
import altair as alt
alt.data_transformers.enable('json')

DataTransformerRegistry.enable('json')

In [2]:
df_episodes = pd.read_csv("C:\\Users\\20203666\\Documents\\GitHub\\data-vis-simpsons\\assignment2\\data\\raw_data\\simpsons_episodes.csv")

In [3]:
df_lines = pd.read_csv("C:\\Users\\20203666\\Documents\\GitHub\\data-vis-simpsons\\assignment2\\data\\raw_data\\simpsons_script_lines.csv")
df_lines = df_lines.merge(
    df_episodes[['id', 'number_in_season', 'season']],
    left_on='episode_id',
    right_on='id',
    how='left'
)
df_lines['word_count'] = pd.to_numeric(df_lines['word_count'], errors='coerce')
df_lines = df_lines[df_lines['word_count'] <= 150]
df_lines.dropna(subset=['raw_character_text', 'normalized_text', 'word_count'], inplace=True)
df_lines.drop(['id_x', 'id_y'], axis=1, inplace=True)
df_lines

C:\Users\20203666\AppData\Local\Temp\ipykernel_10720\2899939509.py:1: DtypeWarning: Columns (4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_lines = pd.read_csv("C:\\Users\\20203666\\Documents\\GitHub\\data-vis-simpsons\\assignment2\\data\\raw_data\\simpsons_script_lines.csv")

,episode_id,number,raw_text,timestamp_in_ms,speaking_line,character_id,location_id,raw_character_text,raw_location_text,spoken_words,normalized_text,word_count,number_in_season,season
0,32,209,"Miss Hoover: No, actually, it was a little of ...",848000,True,464.0,3.0,Miss Hoover,Springfield Elementary School,"No, actually, it was a little of both. Sometim...",no actually it was a little of both sometimes ...,31.0,19,2
1,32,210,Lisa Simpson: (NEAR TEARS) Where's Mr. Bergstrom?,856000,True,9.0,3.0,Lisa Simpson,Springfield Elementary School,Where's Mr. Bergstrom?,wheres mr bergstrom,3.0,19,2
2,32,211,Miss Hoover: I don't know. Although I'd sure l...,856000,True,464.0,3.0,Miss Hoover,Springfield Elementary School,I don't know. Although I'd sure like to talk t...,i dont know although id sure like to talk to h...,22.0,19,2
3,32,212,Lisa Simpson: That life is worth living.,864000,True,9.0,3.0,Lisa Simpson,Springfield Elementary School,That life is worth living.,that life is worth living,5.0,19,2
4,32,213,Edna Krabappel-Flanders: The polls will be ope...,864000,True,40.0,3.0,Edna Krabappel-Flanders,Springfield Elementary School,The polls will be open from now until the end ...,the polls will be open from now until the end ...,33.0,19,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158266,32,204,Miss Hoover: (OFF LISA'S REACTION) I'm back.,831000,true,464,3.0,Miss Hoover,Springfield Elementary School,I'm back.,im back,2.0,19,2
158267,32,205,"Miss Hoover: You see, class, my Lyme disease t...",839000,true,464,3.0,Miss Hoover,Springfield Elementary School,"You see, class, my Lyme disease turned out to ...",you see class my lyme disease turned out to be,10.0,19,2
158268,32,206,Miss Hoover: Psy-cho-so-ma-tic.,842000,true,464,3.0,Miss Hoover,Springfield Elementary School,Psy-cho-so-ma-tic.,psy-cho-so-ma-tic,1.0,19,2
158269,32,207,Ralph Wiggum: Does that mean you were crazy?,844000,true,119,3.0,Ralph Wiggum,Springfield Elementary School,Does that mean you were crazy?,does that mean you were crazy,6.0,19,2
158270,32,208,"JANEY: No, that means she was faking it.",845000,true,4,3.0,JANEY,Springfield Elementary School,"No, that means she was faking it.",no that means she was faking it,7.0,19,2

In [21]:
df_lines[df_lines['raw_character_text'].str.startswith('Bart ', na=False)]

,episode_id,number,raw_text,timestamp_in_ms,speaking_line,character_id,location_id,raw_character_text,raw_location_text,spoken_words,normalized_text,word_count,number_in_season,season
7,32,216,Bart Simpson: Victory party under the slide!,882000,True,8.0,3.0,Bart Simpson,Springfield Elementary School,Victory party under the slide!,victory party under the slide,5.0,19,2
17,32,226,"Bart Simpson: Hey, thanks for your vote, man.",918000,True,8.0,3.0,Bart Simpson,Springfield Elementary School,"Hey, thanks for your vote, man.",hey thanks for your vote man,6.0,19,2
19,32,228,"Bart Simpson: Well, you got that right. (TO TE...",922000,True,8.0,3.0,Bart Simpson,Springfield Elementary School,"Well, you got that right. Thanks for your vote...",well you got that right thanks for your vote g...,10.0,19,2
21,32,230,"Bart Simpson: Well, don't sweat it. Just so lo...",927000,True,8.0,3.0,Bart Simpson,Springfield Elementary School,"Well, don't sweat it. Just so long as a couple...",well dont sweat it just so long as a couple of...,15.0,19,2
23,32,232,Bart Simpson: Lewis?,931000,True,8.0,3.0,Bart Simpson,Springfield Elementary School,Lewis?,lewis,1.0,19,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158186,32,124,"Bart Simpson: (DISMISSING) Aw, Dad. It's just ...",542000,true,8,5.0,Bart Simpson,Simpson Home,"Aw, Dad. It's just a popularity contest.",aw dad its just a popularity contest,7.0,19,2
158188,32,126,"Bart Simpson: Sure, why not?",552000,true,8,5.0,Bart Simpson,Simpson Home,"Sure, why not?",sure why not,3.0,19,2
158190,32,128,"Bart Simpson: (WARMING TO IT) Hm, yeah.",564000,true,8,5.0,Bart Simpson,Simpson Home,"Hm, yeah.",hm yeah,2.0,19,2
158192,32,130,"Bart Simpson: He says, there aren't any easy a...",568000,true,8,5.0,Bart Simpson,Simpson Home,"He says, there aren't any easy answers! I say,...",he says there arent any easy answers i say hes...,14.0,19,2
158211,32,149,"Bart Simpson: (MOCK CONCERN) Me, too, Mom. I t...",668000,true,8,5.0,Bart Simpson,Simpson Home,"Me, too, Mom. I think they're drifting apart.",me too mom i think theyre drifting apart,8.0,19,2

In [22]:
top_characters = df_lines['raw_character_text'].value_counts().head(100).index.tolist()
char_to_del = ['Crowd', 'Narrator', 'Kids', 'Man']
char_to_rep = {'TROY': 'Troy McClure', 'DOLPH': 'Dolph', 'HERB': 'Herb', 'BUCK': 'Buck'}
top_characters

['Homer Simpson',
 'Marge Simpson',
 'Bart Simpson',
 'Lisa Simpson',
 'C. Montgomery Burns',
 'Moe Szyslak',
 'Seymour Skinner',
 'Ned Flanders',
 'Grampa Simpson',
 'Chief Wiggum',
 'Milhouse Van Houten',
 'Krusty the Clown',
 'Nelson Muntz',
 'Lenny Leonard',
 'Apu Nahasapeemapetilon',
 'Waylon Smithers',
 'Kent Brockman',
 'Carl Carlson',
 'Edna Krabappel-Flanders',
 'Dr. Julius Hibbert',
 'Selma Bouvier',
 'Barney Gumble',
 'Rev. Timothy Lovejoy',
 'Sideshow Bob',
 'Gary Chalmers',
 'Groundskeeper Willie',
 'Mayor Joe Quimby',
 'Ralph Wiggum',
 'Comic Book Guy',
 'Patty Bouvier',
 'Otto Mann',
 'Martin Prince',
 'Announcer',
 'Jimbo Jones',
 'Lou',
 'Sideshow Mel',
 'Professor Jonathan Frink',
 'Fat Tony',
 'Kearney Zzyzwicz',
 'Agnes Skinner',
 'Kirk Van Houten',
 'Snake Jailbird',
 'Cletus Spuckler',
 'DOLPH',
 'Crowd',
 'Todd Flanders',
 'Lionel Hutz',
 'Narrator',
 'Miss Hoover',
 'Gil Gunderson',
 'Kids',
 'The Rich Texan',
 'Captain Horatio McCallister',
 'HERB',
 'Manjula Nahasapeemapetilon',
 'Judge Snyder',
 'Rod Flanders',
 'Maude Flanders',
 'Jasper Beardly',
 'Rainier Wolfcastle',
 'Troy McClure',
 'Adult Bart',
 'Kang',
 'Mona Simpson',
 'Helen Lovejoy',
 'Man',
 'Dr. Nick Riviera',
 'Louie',
 'Woman',
 'TROY',
 'Kodos',
 'Luann Van Houten',
 'Eddie',
 'Lurleen Lumpkin',
 'Blue-Haired Lawyer',
 'Declan Desmond',
 'Lindsay Naegle',
 'Young Homer',
 "Homer's Brain",
 'Duffman',
 'Old Jewish Man',
 'Luigi',
 'Mary',
 'Jacques',
 'Michael',
 'Dewey Largo',
 'Brandine Del Roy',
 'Lady Gaga',
 'Hans Moleman',
 'Rabbi Hyman Krustofsky',
 'Squeaky-Voiced Teen',
 'BUCK',
 'Annie Crawford',
 'Artie Ziff',
 'George H.W. Bush',
 'Director',
 'Young Grampa',
 'Marty',
 'Scratchy',
 'Salesman']

In [5]:
df_q1 = df_lines.groupby(['raw_character_text', 'episode_id'])['word_count'].sum().reset_index()
df_q1 = df_q1[df_q1['raw_character_text'].isin(top_characters)]
df_q1

      raw_character_text  episode_id  word_count
270           Adult Bart          53        11.0
271           Adult Bart         449         8.0
272           Adult Bart         495       383.0
273           Adult Bart         520       152.0
274           Adult Bart         548       489.0
...                  ...         ...         ...
20083        Young Homer         274        36.0
20084        Young Homer         308        66.0
20085        Young Homer         411       607.0
20086        Young Homer         481         3.0
20087        Young Homer         516        65.0

[10892 rows x 3 columns]

In [6]:
char_dropdown = alt.binding_select(options=top_characters, name='Character: ')
char_select = alt.selection_point(fields=['raw_character_text'], bind=char_dropdown, value=top_characters[0])

chart = alt.Chart(df_q1).mark_bar(
    size=12 # Optional: adjust bar width for readability
).encode(
    x=alt.X('episode_id:Q', title='Episode Number'),
    y=alt.Y('word_count:Q', title='Words Spoken'), # Use directly, no aggregate
    color=alt.Color('raw_character_text:N', legend=None),
    tooltip=['episode_id', 'word_count']
).add_params(
    char_select
).transform_filter(
    char_select
).properties(
    width=600,
    height=300,
    title="Character Dialogue Volume per Episode"
)

chart.show()

alt.Chart(...)